name: pas_mobile_11pplg1_10
description: "A new Flutter project."
publish_to: 'none' # Jangan publish ke pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.0
  firebase_messaging: ^15.2.10

  # State management
  get: ^4.7.2
  shared_preferences: ^2.3.3

  # UI / Loading
  loading_animation_widget: ^1.3.0
  cupertino_icons: ^1.0.8

  # Database & API
  sqflite: ^2.4.2
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    # Foto user yang ada
    - aset/ambakus.jpg
    - aset/logo_flutter.png
    - aset/image.png
